import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { HydrationSuppressor } from "@/components/HydrationSuppressor";
import { ThemeProvider } from "@/components/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// This function runs on the server
async function getLocale(params: Promise<{ locale: string }>) {
  const { locale } = await params;
  // If needed, you could perform additional validation or transformation here
  return locale;
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  // Properly await the locale parameter
  const locale = await getLocale(params);

  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <HydrationSuppressor>
            <Providers locale={locale}>{children}</Providers>
          </HydrationSuppressor>
        </ThemeProvider>
      </body>
    </html>
  );
}
